#!/bin/sh

# PROVIDE: __NAME__
# REQUIRE: LOGIN postgresql nginx
# KEYWORD:

. /etc/rc.subr
name=__NAME__
rcvar=__NAME___enable
pidfile=__SOCKET__.pid
command=/usr/local/bin/gunicorn-3.6
command_args="-b unix:__SOCKET__ -w 4 -p $pidfile -D website.wsgi"

load_rc_config $name
: ${__NAME___enable:=no}
: ${__NAME___user:=www}
: ${__NAME___group:=www}
: ${__NAME___chdir:=__PDIR__}
: ${__NAME___env:=}

run_rc_command $1
