#!/bin/sh
#
# PROVIDE: __NAME__
# REQUIRE: LOGIN postgresql nginx
# KEYWORD:

. /etc/rc.subr
name=__NAME__
rcvar=${name}_enable
load_rc_config $name

command=__PDIR__/.local/bin/starman
command_args="-l __SOCKET__ --pid /tmp/__NAME__.pid -D bin/app.pl"
pidfile=/tmp/__NAME__.pid
: ${__NAME___enable:=no}
: ${__NAME___user:=www}
: ${__NAME___chdir:=__PDIR__}
: ${__NAME___env:=PERL5LIB=__PDIR__/.local/lib/perl5${PERL5LIB:+:}$PERL5LIB}

run_rc_command $1
