#!/bin/sh
#
# PROVIDE: __NAME__
# REQUIRE: LOGIN postgresql nginx
# KEYWORD:

. /etc/rc.subr
name=__NAME__
rcvar=${name}_enable
load_rc_config $name

command=/usr/local/bin/npm
command_args="start"

: ${__NAME___enable:=no}
: ${__NAME___user:=www}
: ${__NAME___chdir:=__PDIR__}

run_rc_command $1
