#!/bin/sh
#
# PROVIDE: __NAME__
# REQUIRE: LOGIN postgresql nginx
# KEYWORD:

. /etc/rc.subr
name=__NAME__
rcvar=${name}_enable
load_rc_config $name

command=__PDIR__/.local/bin/bundle
command_args="exec unicorn -l __SOCKET__ -E production -D"

: ${__NAME___enable:=no}
: ${__NAME___user:=www}
: ${__NAME___chdir:=__PDIR__}
: ${__NAME___env:=GEM_PATH=__PDIR__/.local}

run_rc_command $1
